version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE_CHARSET=utf8mb4
      - MYSQL_DATABASE_COLLATION=utf8mb4_general_ci
    volumes:
      - /root/docker/data/mysql:/var/lib/mysql
