deploy_env: local
micro:
  register_ttl: 30
  register_interval: 15
  registry: etcd
  registry_address:
    - "192.168.56.189:2379"
logger:
  level: "debug"
  filename: "app.log"
  max_size: 100
  max_backups: 10
  max_age: 7
  compress: false
tracer:
  addr: "192.168.56.189:6831"
hystrix:
  timout: 5000
  max_concurrent: 0
  request_volume_threshold: 0
  sleep_window: 0
  error_percent_threshold: 0
