deploy_env: dev
micro:
  server_name: "go.micro.web.ws"
  server_version: "1.0.0"
  register_ttl: 30
  register_interval: 15
  registry: etcd
  registry_address:
    - "192.168.56.189:2379"
logger:
  level: "debug"
  filename: "app.log"
  max_size: 100
  max_backups: 10
  max_age: 7
  compress: false
tracer:
  addr: "192.168.56.189:6831"
nats:
  addrs:
    - "nats://192.168.56.189:4222"
redis:
  addr: "192.168.56.189:6379"
  password: "123456"
  db: 0
gate_id: 1

